### ISSUE TITLE
url

### ISSUE THREAD

**Issue by BenjiDa** [LSDtopotools/lsdviztools#116]
* lsdviztools version: 0.3.0
* Python version: 3.8.3
* Operating System: Mac OS 10.14.6
* lsdtt installed with docker

### Description

Describe what you were trying to get done.

Download example SRTM data from `SB_DEM.download_pythonic()`

Tell us what happened, what went wrong, and what you expected to happen.

`URLError: <urlopen error [Errno 111] Connection refused>`

### What I Did
Using the example lsdtt notebook `Example_lsdtopotools_analysis.ipynb` I ran `SB_DEM.download_pythonic()` expecting to get a nice pretty dataset. Instead I got `URLError: <urlopen error [Errno 111] Connection refused>` it looks like the urllib request is breaking somewhere.  I was able to fix the problem by using `SB_DEM.download()` but this perhaps is not the best solution in the long run.

**Comment by simon-m-mudd** [comment]
Hi Ben, sadly opentopography changed their API so the pythonic download tool has gone defunct. I haven't got around to doing a workaround yet but will try to do it in the next week.

**Comment by BenjiDa** [comment]
Thanks, these new viztools are 👍  💯  😄  😲

**Comment by simon-m-mudd** [comment]
Fixed this a while ago but forgot to close this issue
