### ISSUE TITLE
lsdtt-chi-analysis command line tool, 'No such file or directory'

### ISSUE THREAD

**Issue by BenjiDa** [LSDtopotools/lsdviztools#119]
* lsdviztools version: 0.3.0
* Python version: 3.8
* Operating System: Mac OS 10.14
* Running lsdviztools in jupyter notebook from docker container

### Description

I am trying to run the command line tool `lsdtt-chi-analysis` from Jupyter Notebook in order to streamline my workflow.  I have successfully been able to get the tool to work directly in the terminal. 

### What I Did

```
lsdtt_parameters = {"minimum_elevation": "0",
                    "minimum_basin_size_pixels": "10000",
                    "maximum_basin_size_pixels": "100000000",
                    "estimate_best_fit_movern_no_bootstrap": "true"
                   }
lsdtt_drive = lsdmw.lsdtt_driver(command_line_tool = "lsdtt-chi-analysis", 
                                 read_prefix = "DEM_SRTM30_UTM",
                                 write_prefix= "movern_DEM",
                                 read_path = "./",
                                 write_path = "./",
                                 parameter_dictionary=lsdtt_parameters)

lsdtt_drive.print_parameters()
```
When I run `lsdtt_drive.run_lsdtt_command_line_tool()` it errors:

`FileNotFoundError: [Errno 2] No such file or directory: 'lsdtt-chi-analysis'`

The confusing thing is this works correctly for both `lsdtt-basic-metrics` and `lsdtt-channel-extraction` command line tools. 

Thanks

**Comment by simon-m-mudd** [comment]
I wrote these in haste and there are a lot of mistakes (and an almost complete lack of testing)! The command should be "lsdtt-chi-mapping". I've updated lsdviztools with the correct command line call. (I will add a new tag once I have sorted the opentopography data download issue).
