### ISSUE TITLE
Wrong EPSG for single-digit UTM zones with lsdmap_gdalio

### ISSUE THREAD

**Issue by jmdelvecchio** [LSDtopotools/lsdviztools#193]
* lsdviztools version: 0.4.11
* Python version: 3.8.16
* Operating System: linux

### Description

Package `utm` (and therefore lsdmap_gdalio) does not add a leading zero to single-digit UTM zones. What should be "EPSG:32603" (UTM 3N) instead gets translated to "EPSG:3263" (Antarctica). 

### What I Did

Here is a [Colab notebook](https://colab.research.google.com/drive/1jrJXGJTLDfz0IFToNox4D0JPQV2ldhH5?usp=sharing) demonstrating the issue. With the `utm` output:

`(544386.0105777784, 6754665.726431849, 3, 'V')`

The 3 just gets tacked on to `EPSG = "326" + str(UTMzone)`. 

In my workflow I use `epsg = int(32700-(np.round((45+lat)/90,0)*100)+np.round((183+long)/6,0))` to get the EPSG code that `utm` is doing under the hood. I think you do something different for the southern hemisphere but I'm looking at permafrost so I just ignore that part 😬 

The result of projecting to 3263 is flow routing that fails and/or memory issues because your resulting DEM is 2-4 GB. But zones 47 and 48 work just fine! This has been driving me crazy but I think I've gotten to the bottom of it.

**Comment by simon-m-mudd** [comment]
Hi Joanmarie
I think there are two instances of this error which I will try to patch next week (the other one is in lsdmap_otgrabber).
If you cannot wait you are welcome to make a pull request.
I might suggest testing if str(UTMzone) has only one character and if so prepending a 0 (that is what I will do if I get to fixing this before you do).

**Comment by simon-m-mudd** [comment]
Fixed all instances of this in 0.4.13
