### ISSUE TITLE
No module named 'pandas.plotting._matplotlib'

### ISSUE THREAD

**Issue by emolihumph** [LSDtopotools/lsdviztools#67]
* lsdviztools version: 
* Python version: 
* Operating System: 

### Description

Trying to run PlotMOverNAnalysis.py after "Calculating Concavity". Rasters & plots are supposed to be output. Error messages instead.

### What I Did
I tried redownloading the entire LSDTT package; rerunning the Chi analysis relevant for the visualisation; and spell-checking EVERYTHING.

root@0065412a2b9c:/LSDTopoTools/LSDMappingTools# python PlotMOverNAnalysis.py -dir /LSDTopoTools/data/Second -fname movern_chi2 -ALL True

Traceback (most recent call last):
  File "PlotMOverNAnalysis.py", line 18, in <module>
    from LSDPlottingTools import LSDMap_MOverNPlotting as MN
  File "/LSDTopoTools/LSDMappingTools/LSDPlottingTools/LSDMap_MOverNPlotting.py", line 34, in <module>
    from LSDPlottingTools import joyplot
  File "/LSDTopoTools/LSDMappingTools/LSDPlottingTools/joyplot.py", line 10, in <module>
    from pandas.plotting._matplotlib.tools import (_subplots, _flatten)
ModuleNotFoundError: No module named 'pandas.plotting._matplotlib'

**Comment by simon-m-mudd** [comment]
1. We have been trying to update the visualisation routines and have migrated to a package lsdviztools. But from the above error message it looks like you are using the older version LSDMappingTools.
2. The error message comes from an update to pandas. I have patched LSDMappingTools to fix this problem (it was already updated in `lsdviztools`). You can update the code with a `git pull` command.
3. If you want the updated version, use `plotmovernanalysis.py` from within `lsdviztools`

**Comment by emolihumph** [comment]
I'm looking for documentation to use `lsdviztools` in the Docker environment - is it available yet?

**Comment by simon-m-mudd** [comment]
I haven't written up the documentation yet. 
But you can use `plotbasicrasters.py` and `plotmovernanalysis.py` in the same way the old LSDMappingTools functions worked.
To install you clone lsdviztools and do a local install: `pip install ./`
There are some basic instructions here: https://hub.docker.com/repository/docker/lsdtopotools/lsdtt_pytools_docker
And a few examples here: https://github.com/LSDtopotools/lsdtt_notebooks
